"""
PSI Cash Flow Dashboard - Auto Refresh
=======================================
PT Prasad Seeds Indonesia

Reads "PSI Cash Monitoring Master.xlsx" and:
  1. Regenerates the "CF Summary" sheet (replaces manual pivot).
  2. Regenerates the "Bank - <Month>" sheets from Beginning Balance entries
     and net change per bank per month.
  3. Writes public/data.json - feeds the live HTML dashboard on Vercel.

Usage:
    python scripts/refresh_dashboard.py

Or use the one-click `refresh.bat` (Windows) which runs this script
and pushes the result to Git so Vercel auto-rebuilds.
"""
from __future__ import annotations

import json
import os
import shutil
import sys
from datetime import datetime
from pathlib import Path

import openpyxl

# Local modules
sys.path.insert(0, str(Path(__file__).parent))
from lib_pivot import (
    read_all_banks, detect_currency_rates, all_periods,
    aggregate_by_path, aggregate_beginning_balance,
    aggregate_net_change_per_bank, build_cf_structure,
)
from lib_excel import write_cf_summary, write_bank_sheets
from lib_dashboard import build_dashboard_data

# -----------------------------------------------------------------------------
# CONFIG
# -----------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent
SOURCE_XLSX = ROOT / "PSI Cash Monitoring Master.xlsx"
PUBLIC_DIR = ROOT / "public"
DATA_JSON = PUBLIC_DIR / "data.json"


def is_excel_open(path: Path) -> bool:
    """Detect Excel lock file (~$filename) which indicates file is open."""
    lock = path.parent / f"~${path.name}"
    return lock.exists()


def main():
    src = Path(os.environ.get("PSI_SOURCE_XLSX", str(SOURCE_XLSX)))
    if not src.exists():
        print(f"ERROR: Source file not found: {src}")
        sys.exit(1)

    if is_excel_open(src):
        print("=" * 70)
        print("WARNING: It looks like the Excel file is currently OPEN in Excel")
        print(f"        ({src.name}).")
        print("        Please close Excel and run this script again so the")
        print("        regenerated CF Summary and Bank sheets can be saved.")
        print("=" * 70)
        sys.exit(2)

    print(f"Reading {src.name} ...")
    wb = openpyxl.load_workbook(src, data_only=True)
    rows = read_all_banks(wb)
    print(f"  {len(rows):,} transactions loaded")

    usd_rate, inr_rate = detect_currency_rates(wb)
    print(f"  Rates: USD = Rp {usd_rate:,.0f}  |  INR = Rp {inr_rate:,.0f}")

    periods = all_periods(rows)
    print(f"  Periods found: {', '.join(periods)}")

    agg = aggregate_by_path(rows)
    bb_agg = aggregate_beginning_balance(rows)
    net_change_agg = aggregate_net_change_per_bank(rows)

    print("Building CF Summary structure ...")
    lines = build_cf_structure(agg, periods)

    print("Writing CF Summary sheet ...")
    write_cf_summary(wb, lines, periods, usd_rate, inr_rate, bb_agg)

    print("Writing Bank - <Month> sheets ...")
    write_bank_sheets(wb, rows, bb_agg, net_change_agg, periods, usd_rate, inr_rate)

    # Backup before save
    backup_dir = ROOT / "backups"
    backup_dir.mkdir(exist_ok=True)
    backup = backup_dir / f"PSI Cash Monitoring Master.{datetime.now():%Y%m%d_%H%M%S}.xlsx"
    shutil.copy2(src, backup)
    print(f"  Backup saved to: {backup.name}")

    wb.save(src)
    print(f"  Saved: {src.name}")

    print("Building dashboard data ...")
    data = build_dashboard_data(rows, agg, bb_agg, net_change_agg,
                                lines, periods, usd_rate, inr_rate)
    PUBLIC_DIR.mkdir(exist_ok=True)
    json_text = json.dumps(data, indent=2, default=str)
    DATA_JSON.write_text(json_text, encoding="utf-8")
    print(f"  Saved: {DATA_JSON.relative_to(ROOT)}")
    # Also write data.js with the same payload assigned to window.PSI_DATA
    # so that double-clicking index.html (file://) works without a web server.
    DATA_JS = PUBLIC_DIR / "data.js"
    js_text = (
        "// Auto-generated by refresh_dashboard.py\n"
        "// Embedded copy of data.json so index.html works when opened locally.\n"
        "window.PSI_DATA = " + json_text + ";\n"
    )
    DATA_JS.write_text(js_text, encoding="utf-8")
    print(f"  Saved: {DATA_JS.relative_to(ROOT)}")

    print("\nRefresh OK. Open public/index.html to view dashboard.")


if __name__ == "__main__":
    main()
